### PR TITLE
Fixed error NG0100 happening on LabelComponent

### PR DESCRIPTION
**Pull request by Licen-it**
Closes carbon-design-system/carbon-components-angular#2459

added `changeDetectorRef.detectChanges()` to trigger a re-evaluation of the changes. Suggested solution from angular is to use `ngAfterContentInit` instead of `ngAfterViewInit` (https://angular.io/errors/NG0100), but I believe afterViewInit was used to catch elements generated by child components that would only appear at that stage. @reviewers if you believe the suggested change from angular might not break current behaviour i'm happy to apply that change instead.

Screenshot of the error:
Screenshot

#### Changelog

**Changed**

* fixed NG0100 error happening when child nodes passed to LabelComponent already define an id

### CODE REVIEW

**Comment by Akshat55** [comment]
Which version of Angular are you seeing this error on @Licen-it? I've tried to reproduce the error but haven't been able to. I've tried with Angular 13 & don't run into this error 🤔

**Comment by Licen-it** [comment]
@Akshat55 (not sure why not seeing your comment here even if i got the email notification...anyway)...i'm using angular 14, but it should appear on 13 as well. Make sure that you are defining an id on the input/textarea/div you are inserting inside the label as it's only appearing when it's reusing the existing id for the `for=` property. Also make sure you are running in development mode as i believe it's suppressed when running in production mode

**Comment by Akshat55** [comment]
I deleted the comment @Licen-it since I reproduced it - I was checking the wrong version of carbon angular. My fault! Sorry about that.

**Review by Akshat55 — APPROVED** [review]

**Comment by Akshat55** [comment]
I've approved the fix!

>  but I believe afterViewInit was used to catch elements generated by child components that would only appear at that stage.

Yes, we are using AfterViewInit to catch `this.wrapper` (ViewChild)... We can alternatively use ElementRef? I'll experiment with that in V11.

**Review by zvonimirfras — APPROVED** [review]

**Pull request merged**
