### PR TITLE
fix: ensure proper namespace for title attr

### LINKED ISSUE #3078: Icon directive is not properly setting the title inside SVG as tooltip
While using the `cdsIcon` directive, I saw that its not properly setting the title attribute so that it comes up as a tooltip when I hover over the icon. Showing tooltip is pretty useful if I want to indicate any helpful text through the icon.

Its pretty much reproducible from the storybook: https://angular.carbondesignsystem.com/?path=/story/components-icon--basic&args=title:sdasdsad

### PR DESCRIPTION
**Pull request by nizamial09**
Browsers may not always render the <title> inside SVG as a tooltip. Ensuring it has a correct namespace improves the cross browser behavior

Closes #3078

#### Changelog

**Changed**

* added proper namespace for `title` attribute

### CODE REVIEW

**Comment by nizamial09** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by nizamial09** [comment]
I saw these errors when I ran `npm run lint`

```
src/combobox/combobox.component.spec.ts:36:9
ERROR: 36:9    quotemark       ' should be "
ERROR: 210:34  quotemark       ' should be "

src/combobox/combobox.component.ts:699:1
ERROR: 699:1   indent          tab indentation expected
ERROR: 700:1   indent          tab indentation expected
ERROR: 701:1   indent          tab indentation expected
ERROR: 702:1   indent          tab indentation expected
ERROR: 703:1   indent          tab indentation expected
ERROR: 704:1   indent          tab indentation expected

src/datepicker/datepicker.stories.ts:171:32
ERROR: 171:32  trailing-comma  Unnecessary trailing comma

```

Unrelated to my PR though

**Comment by Akshat55** [comment]
> I saw these errors when I ran `npm run lint`
> 
> ```
> src/combobox/combobox.component.spec.ts:36:9
> ERROR: 36:9    quotemark       ' should be "
> ERROR: 210:34  quotemark       ' should be "
> 
> src/combobox/combobox.component.ts:699:1
> ERROR: 699:1   indent          tab indentation expected
> ERROR: 700:1   indent          tab indentation expected
> ERROR: 701:1   indent          tab indentation expected
> ERROR: 702:1   indent          tab indentation expected
> ERROR: 703:1   indent          tab indentation expected
> ERROR: 704:1   indent          tab indentation expected
> 
> src/datepicker/datepicker.stories.ts:171:32
> ERROR: 171:32  trailing-comma  Unnecessary trailing comma
> ```
> 
> Unrelated to my PR though

I'll have that resolved in a chore PR!

**Comment by nizamial09** [comment]
> I'll have that resolved in a chore PR!

cool, thanks

**Review by Akshat55 — APPROVED** [review]

**Pull request merged**
