### PR TITLE
fix: replace 'lodash' with 'lodash-es' to reduce bundle size

### PR DESCRIPTION
**Pull request by danielsogl**
#### Changelog

* Replace lodash with 'lodash-es' dependency to reduce bundle size

### CODE REVIEW

**Comment by danielsogl** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by danielsogl** [comment]
recheck

**Comment by Akshat55** [comment]
Hi @danielsogl, any specific reason for removing lodash? I feel like it can bring value to a lot of the components where we need to do array manipulation or deep copies. I agree we can implement our own utilities, but using lodash would be more safer and stable. 

The tests seem to pass so it's definitely safe to remove, just want to know your reasoning and any complications you have run into.

**Review by Akshat55 — COMMENTED** [review]
Hi @danielsogl, any specific reason for removing lodash? I feel like it can bring value to a lot of the components where we need to do array manipulation or deep copies. I agree we can implement our own utilities, but using lodash would be more safer and stable. 

The tests seem to pass so it's definitely safe to remove, just want to know your reasoning and any complications you have run into.

**Comment by danielsogl** [comment]
@Akshat55 `lodash ` adds a huge footprint to the library bundle. Another issue is that `lodash-es` is also added as a dependency to the project. You don’t need to use two implementations of the same library, or you could opt for no implementation at all.

**Comment by Akshat55** [comment]
> @Akshat55 `lodash ` adds a huge footprint to the library bundle. Another issue is that `lodash-es` is also added as a dependency to the project. You don’t need to use two implementations of the same library, or you could opt for no implementation at all. `lodash-es` would keep the bundle small.

You're right, my initial plan was to replace `lodash-es` with just `lodash` but did not take the overall size into account. `lodash-es` is not exported with the code, only `lodash` is, but we can replace this. For now, I think it would be better to replace `lodash` with `lodash-es` instead of completely removing it. What are your thoughts?

**Comment by Akshat55** [comment]
@danielsogl Is it alright if I make changes to this PR to replace `lodash` with `lodash-es`?

**Comment by danielsogl** [comment]
@Akshat55 yes feel free to make changes :)

**Review by Akshat55 — APPROVED** [review]

**Pull request merged**
