### PR TITLE
fix(table): accessibility fix on checkbox

### PR DESCRIPTION
**Pull request by rkkp1023**
Signed-off-by: Ravi Kumar rkkp1023@gmail.com

Closes : https://github.com/carbon-design-system/carbon-components-angular/issues/2237

After this Pr merge You will notice these changes :
-> when you click on checkbox in table you will see outline (Accessibility)

### after

image

### CODE REVIEW

**Comment by rkkp1023** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by rkkp1023** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by rkkp1023** [comment]
recheck

**Comment by Akshat55** [comment]
@ravi-kumar70 @rkkp1023 Thanks for the PR, there seems to be an issue with this PR. Could you please close this PR & remake it where you make the github commit when global/project user.email/user.name is set to your public github instead of IBM github?

**Comment by rkkp1023** [comment]
closing this Pr

**Comment by rkkp1023** [comment]
@Akshat55 created new Pr with the right user . please have a look thanks
https://github.com/carbon-design-system/carbon-components-angular/pull/2487

**Pull request closed without merging**
