### PR TITLE
fix: make pagination text consist on resize

### LINKED ISSUE #2664: pagination controls text missing on window resize
## Detailed description

> Describe in detail the issue you're having.

When resizing the window and decreasing the page width, beyond a certain threshold, the pagination component changes from displaying all relevant information (i.e. items per page, total items count and page number) to just the next/prev page buttons. By comparison, when doing the same to the pagination component from the base carbon components, the number of currently displayed and total items is shown along with the next/prev page buttons.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Pagination Component

> What did you expect to happen? What happened instead? What would you like to see changed?

Expectation was for the count of items on the current page and total items count to be displayed as is done by non-Angular framework. Actual behaviour was that only the next/prev page buttons were displayed. Angular framework's pagination component should be consistent across frameworks.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components@10.58.5
carbon-components-angular@4.73.1

**Issue is reproducible in carbon components angular storybook as well.**

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Supply Chain Intelligence Suite

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/carbon-components-angular-forked-8krh5k?file=/src/app/app.component.ts)

1. Create a page with a pagination component. Specify all the default options for the component.
2. Grab the left or right edge of the window and begin dragging to decrease the width.
3. Beyond a certain threshold, the pagination component is reduced to next/prev page buttons and no text.

### Carbon Components Angular Pagination component when window width decreased
image

### Carbon Components Pagination component when window width decreased
image

### PR DESCRIPTION
**Pull request by kush-savani**
Closes carbon-design-system/carbon-components-angular#2664

On resize of window, pagination information (i.e. items per page, total items count and page number) are getting hide due to media query on `cds--pagination__text` class. I add another class `cds--pagination__items-count` for important pagination information. On smaller size of window, require information will remain on screen.

#### Changelog

**New**

* Add `cds--pagination__items-count` css class to important pagination information display tag.

Before:

https://github.com/carbon-design-system/carbon-components-angular/assets/49565062/92ead07c-a560-433b-83b6-734c115ca2b3

After: 

https://github.com/carbon-design-system/carbon-components-angular/assets/49565062/01135090-0fa2-4f84-b29e-e74c91b50c60

### CODE REVIEW

**Comment by kush-savani** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by kush-savani** [comment]
recheck

**Comment by Akshat55** [comment]
@kush-savani Could you also backport this change into v10?

**Comment by Akshat55** [comment]
We have a v10 branch, which you can fetch from upstream. It is basically CCA v4.

**Pull request merged**
