### PR TITLE
fix: sidenavItem component useRouter should be false by default

### PR DESCRIPTION
**Pull request by klaascuvelier**
Closes carbon-design-system/carbon-components-angular#2851

fixed default value for `useRouter` in `sidenav-item.component.ts`

#### Changelog

**Changed**

* fixed default value for `useRouter` in `sidenav-item.component.ts`

### CODE REVIEW

**Review by Akshat55 — APPROVED** [review]

**Comment by Akshat55** [comment]
Nice catch, that totally went past me 😓

**Comment by klaascuvelier** [comment]
Thanks for the quick review @Akshat55 
I could make a test case for this but I don't know if there's much value in it. Let me know if you'd still want that.

**Comment by Akshat55** [comment]
@klaascuvelier, it should be fine, no need for a test for this case.

**Comment by klaascuvelier** [comment]
> Nice catch, that totally went past me 😓

Same. Noticed styles were broken in storybook and started investigating. Shouldn't have happened, apologies.

**Comment by Akshat55** [comment]
All good! Thanks for quickly creating a PR to fix this.

**Pull request merged**
